Add changelog to launcher
zowe/launcher pull request #100
Opened 2023-10-16 21:42 UTC by struga0258

2023-10-17 04:59 UTC, timgerstel approved these changes

2023-10-17 11:54 UTC, DivergentEuropeans submitted a review, later dismissed
Missed some potential replaces from copy-paste

2023-10-17 11:54 UTC, DivergentEuropeans commented on CHANGELOG.md
> +# Zlux Server Framework Changelog
Change to "Zowe Launcher Changelog"

2023-10-17 11:54 UTC, DivergentEuropeans commented on CHANGELOG.md
> +All notable changes to the Zlux Server Framework package will be documented in this file..
Change to "[...] notable changes to the Zowe Launcher will be documented"

2023-10-17 19:11 UTC, 1000TurquoisePogs requested changes, later dismissed

2023-10-17 19:11 UTC, 1000TurquoisePogs commented on CHANGELOG.md
> +## 2.14.0
this version does not exist.

2023-10-18 15:08 UTC, DivergentEuropeans approved these changes

2023-10-18 15:09 UTC, merged